# Generated by Django 4.2.4 on 2023-08-21 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpannel', '0002_aboutus_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aboutus',
            old_name='status',
            new_name='is_active',
        ),
    ]
