# Generated by Django 4.2.4 on 2023-08-22 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminpannel', '0003_rename_status_aboutus_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='designations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designations_title', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='speakers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speakers_pic', models.ImageField(blank=True, null=True, upload_to='speaker/')),
                ('speakers_name', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('mobile', models.CharField(max_length=12)),
                ('facebook', models.CharField(blank=True, max_length=255, null=True)),
                ('twitter', models.CharField(blank=True, max_length=255, null=True)),
                ('linkedin', models.CharField(blank=True, max_length=255, null=True)),
                ('pinterest', models.CharField(blank=True, max_length=255, null=True)),
                ('approved', models.BooleanField(default=False)),
                ('speakers_designation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminpannel.designations')),
            ],
        ),
    ]
