# Generated by Django 4.2.4 on 2023-08-27 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpannel', '0004_designations_speakers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='speakers',
            old_name='speakers_designation',
            new_name='desi',
        ),
        migrations.RenameField(
            model_name='speakers',
            old_name='approved',
            new_name='is_active',
        ),
    ]
