# Generated by Django 4.2.4 on 2023-09-02 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpannel', '0006_remove_speakers_desi_remove_speakers_email_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='speakers',
        ),
    ]
