# Generated by Django 4.2.4 on 2023-09-02 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpannel', '0007_delete_speakers'),
    ]

    operations = [
        migrations.CreateModel(
            name='speaker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speaker_pic', models.ImageField(blank=True, null=True, upload_to='about/')),
                ('speaker_title', models.CharField(max_length=200)),
                ('speaker_description_1', models.TextField(blank=True, null=True)),
                ('speaker_description_2', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
    ]
