# Generated by Django 4.2.4 on 2023-09-02 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpannel', '0009_alter_aboutus_about_title_alter_speaker_speaker_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speaker',
            name='speaker_title',
            field=models.CharField(default=False, max_length=200),
        ),
    ]
