# Generated by Django 4.2.4 on 2023-09-02 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpannel', '0011_alter_speaker_speaker_pic'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='speaker',
            new_name='speakers',
        ),
    ]
