# Generated by Django 4.2.4 on 2023-09-02 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpannel', '0012_rename_speaker_speakers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speakers',
            name='speaker_pic',
            field=models.ImageField(blank=True, null=True, upload_to='speaker/'),
        ),
    ]
