# Generated by Django 4.2.4 on 2023-09-06 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpannel', '0013_alter_speakers_speaker_pic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='speakers',
            old_name='speaker_title',
            new_name='speaker_name',
        ),
    ]
