# Generated by Django 4.2.4 on 2023-09-06 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpannel', '0016_speakers_twitter'),
    ]

    operations = [
        migrations.AddField(
            model_name='speakers',
            name='linkedin',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='speakers',
            name='pinterest',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
