# Generated by Django 4.2.4 on 2023-08-19 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='aboutus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_pic', models.ImageField(blank=True, null=True, upload_to='about/')),
                ('about_title', models.CharField(max_length=200)),
                ('about_description_1', models.TextField(blank=True, null=True)),
                ('about_description_2', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
