# Generated by Django 4.2.4 on 2023-08-20 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontendApp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='aboutus',
        ),
    ]
